DHIS2_DATA_ELEMENT_ID: DizZIhvzUC6
DHIS2_DRY_RUN: True

IMPORT_VARIABLE: 2m_temperature
IMPORT_VALUE_COL: t2m
IMPORT_IS_CUMULATIVE: False
IMPORT_FROM_UNITS: kelvin
IMPORT_TO_UNITS: degC

IMPORT_START_DATE: 2025-08
IMPORT_END_DATE: 2025-08

DOWNLOAD_FOLDER: ../../data/local
DOWNLOAD_PREFIX: era5_hourly_temperature_sierra_leone
TEMPORAL_AGGREGATION: mean